### ISSUE TITLE
SquareCrop strategy

### ISSUE THREAD

**Issue by BuRr-Lee** [sennnnn/OpenVIS#1]
Hi, I wonder where the code of your SquareCrop strategy is?

**Comment by clownrat6** [comment]
Hello, thanks for your issue.
The inference crop strategy of openvis is implemented in the `_preprocess_image` function of [adapter.py](https://github.com/sennnnn/OpenVIS/blob/46f78f041bd52506509b7f54048f3c267b68f443/openvis/modeling/clip_adapter/adapter.py#L73). The ROIAlign is actually a efficient SquareCrop strategy implementation.
