### ISSUE TITLE
mask_adapted_clip

### ISSUE THREAD

**Issue by SCYF123** [sennnnn/OpenVIS#2]
Hello, this is a very good job. I would like to inquire about the 'pip install -e third_parties/mask_adapted_clip' in the installation guide. I couldn't find this folder. Looking forward to your reply.

**Comment by clownrat6** [comment]
Thanks for your issue. I feel sorry for my mistake. The "mask_adapted_clip/" folder is uploaded.

**Comment by SCYF123** [comment]
Thank you for your reply！

**Comment by clownrat6** [comment]
Hello 👋, If you feel this repo helps your research or work, could you give me a star?
